spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OAuth
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 500000
      max-lifetime: 540000
      connection-test-query: SELECT 1
  devtools:
    restart:
      enabled: true
      additional-paths: target\classes\config\application.yml


eureka:
  instance:
#    instance-id: ${spring.application.name}:${instanceId:${random.value}}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8999/eureka

authorization:
  url: http://auth-server:${server.port}

logging:
  level:
    root: info
    org.springframework.security: debug

#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans

client:
  redirectUrl: http://localhost:5173/