spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  devtools:
    restart:
      enabled: true
      additional-paths: target/classes/**

eureka:
  instance:
    #    instance-id: ${spring.application.name}:${instanceId:${random.value}}}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8999/eureka/

logging:
 level:
   root: info
   org.springframework.security: trace

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans