spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 1000
      lettuce:
        pool:
          max-idle: 15
          max-active: 20
          min-idle: 5
          max-wait: 500
          time-between-eviction-runs: 200
  devtools:
    restart:
      enabled: true
      additional-paths: target/classes/**
  security:
    oauth2:
      client:
        registration:
          messaging_gateway_oidc:
            provider: messaging_gateway_oidc
            clientId: gateway_client
            clientSecret: gateway_client_secret
            scope:
              - openid
              - profile
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          messaging_gateway_oidc:
            issuer-uri: http://auth-server:9000
            userInfoUri: http://auth-server:9000/userinfo
            tokenUri: http://auth-server:9000/oauth2/token
            authorizationUri: http://auth-server:9000/oauth2/authorize
            jwkSetUri: http://auth-server:9000/oauth2/jwks

eureka:
  instance:
    #    instance-id: ${spring.application.name}:${instanceId:${random.value}}}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8999/eureka/

logging:
 level:
   root: info
   org.springframework.security: trace

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans