spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  devtools:
    restart:
      enabled: true
      additional-paths: target\classes\config\application.yml

logging:
 level:
   root: info
   org.springframework.security: trace