spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  devtools:
    restart:
      enabled: true
      additional-paths: target/classes/**

logging:
 level:
   root: info
   org.springframework.security: trace

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans