

logging:
  level:
    root: info
    org.springframework.security: trace

spring:
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8999/eureka
>>>>>>> 2df7f9afef692b0c3ee21ff6c4495e172cd40748
