
logging:
  level:
    root: info
    org.springframework.security: trace

spring:
  data:
    redis:
      host: localhost
      port: 6379


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8999/eureka
